[package]
name = "Asterisk"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
notify = "7.0.0"
rayon = "1.5"
sha2 = "0.10.8"
whoami = "1.2"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[[bin]]
name = "ast"
path = "src/main.rs"
